service: puller
runtime: python27
api_version: 1
threadsafe: true
instance_class: B1

libraries:
- name: flask
  version: 0.12

handlers:
- url: /.*
  script: main.app
  
manual_scaling:
  instances: 1

includes:
  - env_variables.yaml